language: node_js
node_js:
  - "8"
cache: npm
script:
    - npm run build
install:
  - npm install -g firebase-tools
  - npm i
after_success:
  - firebase deploy --project chromdays --token $FIREBASE_TOKEN
branches:
  only:
    - master
